train:
  _target_: src.datasets.DigiCamDataset
  dataset_length: 10
  name: "train"
  instance_transforms: ${transforms.instance_transforms.train}
test:
  _target_: src.datasets.DigiCamDataset
  dataset_length: 10
  name: "train"
  instance_transforms: ${transforms.instance_transforms.inference}
