defaults:
  - model: ADMM
  - metrics: digi
  - datasets: eval_digicam
  - dataloader: example
  - transforms: digi_trans
  - _self_
inferencer:
  device_tensors: ["lensed", "lensless", "psf"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "save_outputs" # any name here, can be a dataset name
  seed: 1
  skip_model_load: True
  names_for_save: ["reconstructed", "lensless"]
