defaults:
  - model: ADMM
  - metrics: digi
  - datasets: eval_digicam
  - dataloader: example
  - transforms: example
  - _self_
inferencer:
  device_tensors: ["lensed", "lensless", "psf"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "example" # any name here, can be a dataset name
  seed: 1
  skip_model_load: True # path to the pretrained model
