defaults:
  - model: pred_post_ADMM
  - writer: cometml
  - metrics: digi
  - datasets: train_digicam
  - dataloader: example
  - transforms: digi_trans
  - _self_
optimizer:
  _target_: torch.optim.Adam
  lr: 1e-4
loss_function:
  _target_: src.loss.LossAcum
  weights:
    lossL2: 1.0
    lossLPIPS: 0.1
  list_of_losses:
    - _target_: src.loss.MSE_loss
    - _target_: src.loss.LPIPS_loss
      device: "auto"
trainer:
  log_step: 50
  n_epochs: 25
  epoch_len: 500
  device_tensors: ["lensed", "lensless", "psf"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "off" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
